version: '3.8'

services:
  shelfstone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shelfstone_server
    ports:
      - "8080:8080"
    volumes:
      - ./books:/app/books  # Map local ./books directory to /app/books in the container
      - ./data:/app/data    # Map local ./data to /app/data for database and covers
    environment:
      - GIN_MODE=release # Optional: set Gin to release mode
    # If Calibre is very resource-intensive, consider adding resource limits:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: '2G'

# Optional: Define a named volume if you prefer Docker to manage the data persistence
# volumes:
#   shelfstone_data:
#   shelfstone_books: # Though for books, local mapping is usually more convenient for adding files
