services:
  shelfstone-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6336:8080"
    volumes:
      - ./calibre_library:/calibre-library
    networks:
      - shelfstone-net

networks:
  shelfstone-net:
    driver: bridge
